Repository ducvui2003/android-delivery-react-native, pull requests merged in 2024-09, with the labels that each got.

#6 feature/review-screen
  App.tsx
  assets/images/icons/SolarCheckBold.tsx
  assets/images/icons/SolarStarBold.tsx
  assets/images/icons/SolarUserCircleBold.tsx
  src/components/rating/IconRating.tsx
  src/components/rating/IconRatingItem.tsx
  src/components/rating/LineRating.tsx
  src/components/rating/LineRatingItem.tsx
  src/components/rating/type/iconRating.props.ts
  src/components/rating/type/iconRatingItem.props.ts
  src/components/rating/type/lineRating.props.ts
  src/components/rating/type/lineRatingItem.props.ts
  src/components/review/ButtonReview.tsx
  src/components/review/ReviewDisplayItem.tsx
  src/components/review/type/buttonReview.props.ts
  src/components/review/type/reviewDisplayItem.props.ts
  src/configs/themes/DarkTheme.ts
  src/configs/themes/LightTheme.ts
  src/fragments/home/HomeProductsFragment.tsx
  src/fragments/productDetail/ProductDetailAdditionalOption.tsx
  src/navigations/stack.type.ts
  src/screens/AddNewLocationScreen.tsx
  src/screens/CategoriesScreen.tsx
  src/screens/MyLocationScreen.tsx
  src/screens/ProductDetailScreen.tsx
  src/screens/ReviewScreen.tsx
  src/screens/SearchScreen.tsx
  src/screens/SettingPinSecurityScreen.tsx
  src/screens/VerificationScreen.tsx
  src/screens/WelcomeScreen.tsx
  src/screens/mainSubScreens/home/HomeScreen.android.tsx
  src/types/theme.type.ts
  src/utils/formator.ts
Labels: enhancement

#7 feature/my-basket
  App.tsx
  assets/images/icons/SolarArrowAlt.tsx
  assets/images/icons/SolarArrowRightOutline.tsx
  assets/images/icons/SolarDismiss.tsx
  assets/images/icons/SolarMapPointBold.tsx
  assets/images/icons/SolarPenBold.tsx
  assets/images/icons/SolarTicketSaleBold.tsx
  assets/images/icons/SolarWalletBold.tsx
  src/components/basket/BasketItem.tsx
  src/components/basket/MenuBasketItem.tsx
  src/components/basket/OptionAdd.tsx
  src/components/basket/type/basketItem.props.ts
  src/components/basket/type/menuItem.props.ts
  src/components/basket/type/optionAdd.props.ts
  src/components/gradientBorder/GradientBorder.android.tsx
  src/components/gradientBorder/GradientBorder.web.tsx
  src/components/gradientBorder/type/gradient.props.ts
  src/components/gradientBorder/type/position.props.ts
  src/components/input/InputNumberButton.tsx
  src/components/input/type/inputNumberButton.props.ts
  src/components/navigation/type/bottomNavigation.props.ts
  src/configs/themes/DarkTheme.ts
  src/configs/themes/LightTheme.ts
  src/fragments/basket/BasketCalculator.tsx
  src/fragments/basket/BasketMenuFragment.tsx
  src/fragments/productDetail/ProductDetailFooter.tsx
  src/navigations/stack.type.ts
  src/screens/BasketScreen.tsx
  src/types/product.type.ts
  src/types/theme.type.ts
Labels: enhancement

#17 feat: Hoàn thành trang LikedScreen.android.tsx
  App.tsx
  src/components/category/CategoryItem.tsx
  src/components/category/type/category.props.ts
  src/fragments/SearchFragment.tsx
  src/screens/SearchScreen.tsx
  src/screens/mainSubScreens/liked/LikedScreen.android.tsx
  src/types/category.type.ts
Labels: enhancement

#15 feature/payment
  App.tsx
  assets/data/promotion/promotion.ts
  assets/icon.png
  assets/images/confetti.png
  assets/images/heart.png
  assets/images/icons/LogosApple.tsx
  assets/images/icons/LogosGoogePay.tsx
  assets/images/icons/LogosMoney.tsx
  assets/images/icons/LogosPaypal.tsx
  assets/images/icons/LogosVisa.tsx
  assets/images/icons/SolarCalendar.tsx
  assets/images/icons/SolarQuestionCircleBold.tsx
  assets/images/icons/SolarTicketSaleBold.tsx
  assets/images/icons/google_pay.png
  assets/images/icons/money.png
  ios/DeliveryReactNativeApp.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  ios/DeliveryReactNativeApp.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  package.json
  src/components/modal/Modal.tsx
  src/components/modal/type/modal.props.ts
  src/components/payment/ButtonPaymentMethod.tsx
  src/components/payment/CardNumber.tsx
  src/components/payment/CardVisa.tsx
  src/components/payment/Cell.tsx
  src/components/payment/type/buttonPaymentMethod.props.ts
  src/components/payment/type/cardNumber.props.ts
  src/components/payment/type/cardVisa.Props.ts
  src/components/payment/type/cell.Props.ts
  src/components/popUp/PopUp.tsx
  src/components/popUp/type/popUp.props.ts
  src/components/promotion/Promotion.tsx
  src/components/promotion/type/promotion.props.ts
  src/configs/colors/color-template.config.ts
  src/configs/themes/DarkTheme.ts
  src/configs/themes/LightTheme.ts
  src/fragments/paymentMethod/AddPaymentMethodFragment.tsx
  src/hooks/redux/rating.slice.ts
  src/navigations/stack.type.ts
  src/screens/DriverRatingScreen.tsx
  src/screens/InformationPromotionScreen.tsx
  src/screens/MeatRatingScreen.tsx
  src/screens/PaymentMethodScreen.tsx
  src/screens/PromotionScreen.tsx
  src/types/cardVisa.type.ts
  src/types/meatRatingForm.type.ts
  src/types/paymentMethod.type.ts
  src/types/promotion.type.ts
  src/types/ratingForm.type.ts
  src/types/theme.type.ts
Labels: enhancement

#18 feat: complete UI promotion functional
  App.tsx
Labels: enhancement

#28 feat: create ui notification functional
  App.tsx
  assets/data/notification/notification.ts
  assets/data/wishlist/wishlist.ts
  assets/images/icons/MdiDot.tsx
  assets/images/icons/MdiTickCircle.tsx
  assets/images/icons/MdiUserCircle.tsx
  assets/images/icons/SolarCardBold.tsx
  assets/images/icons/SolarCloseCircleBold.tsx
  assets/images/icons/SolarScooterBold.tsx
  assets/images/icons/SolarShopBold.tsx
  assets/images/icons/SolarTicketSaleBold.tsx
  src/components/notification/NotificationCard.tsx
  src/components/notification/type/notifications.props.ts
  src/screens/MainScreen.tsx
  src/screens/PromotionScreen.tsx
  src/screens/mainSubScreens/notification/NotificationScreen.android.tsx
  src/types/notification.type.ts
Labels: enhancement

#29 feature/card_visa
  App.tsx
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/lamnguyen1305/deliveryreactnativeapp/MainApplication.kt
  android/app/src/main/java/com/lamnguyen1305/deliveryreactnativeapp/fragment/AfterCardVisaFragment.kt
  android/app/src/main/java/com/lamnguyen1305/deliveryreactnativeapp/fragment/BeforeCardVisaFragment.kt
  android/app/src/main/java/com/lamnguyen1305/deliveryreactnativeapp/fragment/CardVisaFragment.kt
  android/app/src/main/java/com/lamnguyen1305/deliveryreactnativeapp/fragment/CellFragment.kt
  android/app/src/main/java/com/lamnguyen1305/deliveryreactnativeapp/packages/CardVisaPackage.kt
  android/app/src/main/java/com/lamnguyen1305/deliveryreactnativeapp/utils/ConvertUtils.kt
  android/app/src/main/java/com/lamnguyen1305/deliveryreactnativeapp/view_manager/CardVisaViewManager.kt
  android/app/src/main/res/drawable/bg_gradient_1.xml
  android/app/src/main/res/drawable/bg_gradient_2.xml
  android/app/src/main/res/drawable/ic_visa.xml
  android/app/src/main/res/layout/fragment_after_card_visa.xml
  android/app/src/main/res/layout/fragment_before_card_visa.xml
  android/app/src/main/res/layout/fragment_card_visa.xml
  android/app/src/main/res/layout/fragment_cell.xml
  android/app/src/main/res/values/styles.xml
  src/components/payment/Cell.tsx
  src/components/payment/NativeCardVisaView.tsx
  src/fragments/paymentMethod/AddPaymentMethodFragment.tsx
  src/navigations/stack.type.ts
  src/screens/PaymentMethodScreen.tsx
Labels: documentation, good first issue

#30 faet: Hoàn thành trang TouchIDScreen.tsx và FaceIDScreen.tsx
  App.tsx
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/assets/fonts/Roboto-Black.ttf
  android/app/src/main/assets/fonts/Roboto-BlackItalic.ttf
  android/app/src/main/assets/fonts/Roboto-Bold.ttf
  android/app/src/main/assets/fonts/Roboto-BoldItalic.ttf
  android/app/src/main/assets/fonts/Roboto-Italic.ttf
  android/app/src/main/assets/fonts/Roboto-Light.ttf
  android/app/src/main/assets/fonts/Roboto-LightItalic.ttf
  android/app/src/main/assets/fonts/Roboto-Medium.ttf
  android/app/src/main/assets/fonts/Roboto-MediumItalic.ttf
  android/app/src/main/assets/fonts/Roboto-Regular.ttf
  android/app/src/main/assets/fonts/Roboto-Thin.ttf
  android/app/src/main/assets/fonts/Roboto-ThinItalic.ttf
  android/app/src/main/res/drawable-hdpi/splashscreen_image.png
  android/app/src/main/res/drawable-mdpi/splashscreen_image.png
  android/app/src/main/res/drawable-xhdpi/splashscreen_image.png
  android/app/src/main/res/drawable-xxhdpi/splashscreen_image.png
  android/app/src/main/res/drawable-xxxhdpi/splashscreen_image.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  android/app/src/main/res/values/strings.xml
  android/build.gradle
  android/settings.gradle
  app.json
  assets/adaptive-icon.png
  assets/icon.png
  assets/images/icons/IonScan.tsx
  assets/images/icons/SolarFaceScan.tsx
  assets/images/icons/SolarFaceScanCircleBroken.tsx
  assets/images/icons/SolarFingerScan.tsx
  assets/splash.png
  google-services.json
  ios/DeliveryReactNativeApp.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  ios/DeliveryReactNativeApp.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  package.json
  src/navigations/stack.type.ts
  src/screens/FaceIDScreen.tsx
  src/screens/TouchIDScreen.tsx
  src/utils/CodeColor.ts
Labels: feat

#32 Finish base order screen
  App.tsx
  assets/data/location/location.ts
  assets/data/order/order.ts
  assets/images/icons/FluentLocation16Filled.tsx
  assets/images/icons/SolarMageImageFill.tsx
  assets/images/icons/SolarMenuDotLinear.tsx
  src/components/orderDetail/BoxInfoNecessary.tsx
  src/components/orderDetail/InputReviewArea.tsx
  src/components/orderDetail/OptionsProductCard.tsx
  src/components/orderDetail/ProductOrderCard.tsx
  src/components/orderDetail/type/boxInfoNecessary.props.ts
  src/components/orderDetail/type/productOrderCard.props.ts
  src/components/orders/ButtonFilter.tsx
  src/components/orders/Order.tsx
  src/components/orders/OverlappingImages.tsx
  src/components/orders/StatusLabel.tsx
  src/components/orders/type/buttonFilter.props.ts
  src/components/orders/type/order.props.ts
  src/components/orders/type/overlappingImages.props.ts
  src/navigations/stack.type.ts
  src/screens/MainScreen.tsx
  src/screens/OrderDetailScreen.tsx
  src/screens/mainSubScreens/order/OrderScreen.android.tsx
  src/types/order.type.ts
  src/types/orderDetail.type.ts
Labels: enhancement

#33 Finish base cancel order screen
  App.tsx
  assets/data/order/order.ts
  src/components/orderDetail/OptionsProductCard.tsx
  src/components/orderDetail/ProductOrderCard.tsx
  src/navigations/stack.type.ts
  src/screens/CancelOrderScreen.tsx
  src/screens/OrderDetailScreen.tsx
  src/screens/PaymentMethodScreen.tsx
  src/screens/mainSubScreens/order/OrderScreen.android.tsx
  src/types/orderDetail.type.ts
Labels: enhancement
